# Generated by Django 4.1.2 on 2023-06-26 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_quezada_lopez', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='producto',
            new_name='Productos',
        ),
    ]
