# Generated by Django 4.1.2 on 2023-06-26 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_quezada_lopez', '0002_rename_producto_productos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='apellido',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='productos',
            old_name='comuna',
            new_name='nombre_produ',
        ),
        migrations.RenameField(
            model_name='productos',
            old_name='nombre',
            new_name='valor',
        ),
    ]
