# Generated by Django 4.1.2 on 2023-06-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quezada_lopez', '0003_rename_apellido_productos_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='foto',
            field=models.ImageField(default="{% static 'app_quezada_lopez/imagenes/ima_venta/primera.jpeg' %}", upload_to='productos'),
        ),
    ]
