# Generated by Django 4.1.2 on 2023-06-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quezada_lopez', '0004_productos_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='foto',
            field=models.ImageField(null=True, upload_to='ima_venta'),
        ),
    ]
