# Generated by Django 4.2.2 on 2023-06-27 06:32

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app_quezada_lopez', '0005_alter_productos_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAdminGroup',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.AlterField(
            model_name='productos',
            name='foto',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='productos',
            name='valor',
            field=models.ImageField(max_length=40, upload_to=''),
        ),
    ]
