# Generated by Django 4.2.2 on 2023-06-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quezada_lopez', '0006_customadmingroup_alter_productos_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='valor',
            field=models.IntegerField(max_length=40),
        ),
    ]
