# Generated by Django 4.2.2 on 2023-06-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quezada_lopez', '0007_alter_productos_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='valor',
            field=models.IntegerField(),
        ),
    ]
